### PR TITLE
Prepare composer packagist compability

### PR DESCRIPTION
**Pull request by bcremer**
Prepare repo so it can be installed via `composer require viison/address-splitter`.

Feel free to decline if that is out of scope of this library. But I think it would serve a lot of people better if it was installable via composer/packagist.

### CODE REVIEW

**Comment by andrewisplinghoff** [comment]
Thanks a lot!

**Comment by bcremer** [comment]
Awesome, thanks for merging this.

Can you also submit this library to https://packagist.org/ so it is actually installable using `composer require viison/address-splitter `.

**Comment by andrewisplinghoff** [comment]
Yeah I just did that. Auto-update via a webhook is also on its way, I just cannot setup this myself.

**Comment by samuelvogel** [comment]
Done as well!

**Pull request merged**
